### ISSUE TITLE
Roblox API

### ISSUE THREAD

**Issue by Sanjay-B** [RobloxAPI/rbxapi#1]
I saw that you created a(n) Roblox API library for Go-lang. I want to get in touch with you. 

I couldn't express much of what I wanted to say in this short body. Please have a look at [this](https://forum.roblox.com/Forum/ShowPost.aspx?PostID=221414751) for more information.

The link is a Roblox forum link if you don't like forums, I'd gladly explain
more to you here. 

Hope to hear your response soon! :)

**Comment by Anaminus** [comment]
> ##### ############roblox.com/############################
Can you clarify this?

I currently maintain automatically generated API dumps in raw and JSON formats. I'm not sure if this is what you're looking for, but the endpoints for the latest versions are available here:

- https://anaminus.github.io/rbx/raw/api/latest.txt
- https://anaminus.github.io/rbx/json/api/latest.json

I also maintain a history of past dumps, but I wont guarantee the availability of them. I'll only guarantee the above URLs, since a handful of people actually use them.

The full details are available here:
https://anaminus.github.io/rbx/

**Comment by Sanjay-B** [comment]
``http://wiki.roblox.com/index.php?title=Web_APIs``
Roblox decided to block one of their own link. I'm so sorry about that.

Anywho, I am looking for that but in addition I'm looking for something else. 

Me and a couple of other developers( who made public roblox libraries/wrappers ) are trying to align them into a convenient place to help user's find them easily. I was wondering if you created a roblox library of some sort. If you did or is willing to make one, could you please join our server here. [ https://discord.gg/EDXNdAT ]. 

The server allows for user's to communicate with library/wrapper developers and allows for developers to promote their library/wrapper. It's a small but strong effort. The server was created this morning.

**Comment by Anaminus** [comment]
The main problem is that many of these APIs aren't officially front-facing. That is, their details are allowed to change, and they have no obligation to even continue existing. They're non-public services meant to be used only by Roblox. As a result, maintaining a library that binds to these kinds of APIs is costly in time and effort. I am unwilling to participate for this reason.

I've made [such a library](https://github.com/Anaminus/rbxweb) in the past, but it suffers from the problems I'm describing. An API changes or disappears, causing the library to break. It also lacks a framework that makes it easier to adapt to the instability of the APIs it depends on, making it even more costly to maintain.

**Comment by Sanjay-B** [comment]
I agree. I feel that a majority of the reason is that Roblox see's no reason to keep developers in mind when updating their API is strictly because they simply don't know that these libraries/wrappers exist. If more developers created such libraries/wrappers public, it would bring about a purpose. 

Futhermore, I'm aware that libraries/wrappers are timely and costly to create but, with most APIs they change frequently. As stated, if we prove the existence of such libraries/wrappers to the point that Roblox takes notice, then they could announce before-hand that such changes are taking place. 

>  An API changes or disappears, causing the library to break. It also lacks a framework that makes it easier to adapt to the instability of the APIs it depends on, making it even more costly to maintain.

Adding on to your statement, I completely agree. However, like I said before(body paragraph), if Roblox knew about these libraries/frameworks, maybe they would put more time into developing something for developers to use such as a framework. 

Hopefully, with all this in mind, they may open up more web-apis for us(developers) to use.

**Comment by Anaminus** [comment]
I think your initial question has been answered, so I'm going to close this.

I agree that Roblox would consider implementing their own public API if there were enough interest. But it's not so much about awareness as it is the cost of maintaining a public API to begin with. A maintainer must ensure that their API remains compatible, consistent, stable, and up to date with internal infrastructure. It's a lot more involved than it appears. Your efforts boil down to moving this maintenance cost from Roblox to a third-party (yourselves), which is commendable, but you ought to be aware of what it entails.

These non-public APIs don't have such requirements, because Roblox already controls the only client that matters (the website). When the needs of the client change, Roblox can change their APIs with them. The only reason these APIs are accessible to third-parties is because users (web browsers) must be able to access them on behalf of the client (the website). There are no guarantees for clients that Roblox does not control, so these clients have no choice but to be flexible.

**Comment by Sanjay-B** [comment]
> But it's not so much about awareness as it is the cost of maintaining a public API to begin with. A maintainer must ensure that their API remains compatible, consistent, stable, and up to date with internal infrastructure.

Completely agree. The official [web apis](http://wiki.roblox.com/index.php?title=Web_APIs) haven't changed this this article was published. For the most part, those remain as stable as "Roblox standards" goes. 

If more developers put time into creating libraries/wrappers then, it would bring some incentive to make a public API. However, if Roblox expanded their chat features, developers could bridge that with other services(stack, discord, twitter, etc) or even some games. In the long run, this would allow developers to take advantage of rich content. The same could be applied to studio. If Roblox allowed for developers to edit properties in-game, then that would be a huge plus side for us. Same goes for database-support with datastores. 

Creating a library/wrapper would bring about these features. Waiting for them(proven in the past), just doesn't get work done. Creating one allows other services to connect to Roblox(reason I made one) and would be useful as Roblox updates throughout the years.

>I've made such a library in the past, but it suffers from the problems I'm describing.

You're welcome to join the server and provide api dump updates and promote your [old library](https://github.com/Anaminus/rbxweb) which was written in Go-lang.
